"
" BEGIN VUNDLE
"
"
" You will need to install Vundle, instructions here:
" https://github.com/VundleVim/Vundle.vim#quick-start
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" Plugin for text completion
" You will need to build YCM Core, see instructions here:
" https://github.com/Valloric/YouCompleteMe#linux-64-bit
Plugin 'Valloric/YouCompleteMe'
set completeopt-=preview
let g:ycm_clangd_args = ['--noclang-tidy'] " Wish I could configure it to be less aggressive

" Many nice colorschemes
Plugin 'rafi/awesome-vim-colorschemes'

" Better Python syntax highlighting
Plugin 'vim-python/python-syntax'

" XML tag completion
Plugin 'sukima/xmledit'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

"
" END VUNDLE
"

" Use utf-8 for everything.
" Watch out if working with non-utf 8 files, since
" these settings will auto convert them
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8 " Forces keystrokes to be interpreted as utf-8


" Copy indentation of the previous line
set autoindent
" Auto detect indenting style based on file extension
filetype plugin indent on

" Use 4-space indents
set shiftwidth=4
" Replace TAB with a 4-space indent
set expandtab
" Treat 4 consecutive spaces as a 'soft tab', so backspace dedents.
set softtabstop=4

" Show the actual TAB character as 8 spaces wide
" (helps distinguish from 4-space indents)
set tabstop=8


" Tell Vim how many colours to use.
" 
" These days, most terminals will support true colour (24-bit colours)
" out of the box, but if you want a more portable but still pretty vimrc,
" set to 256, like this:
" set t_Co=256
" set t_AB=[48;5;%dm
" set t_AF=[38;5;%dm
" set term=xterm-256color
" set t_ut=
"
" However, boy do I love rainbows, so let's support true colour
" see :h xterm-true-color for more info
set termguicolors

" Enable syntax highlighting
syntax on

" Vim guesses the language from the extension to apply syntax highlighting
" The defaults are fairly comprehensive, but if you need to you can add
" more extensions like so:
" autocmd BufNewFile,BufRead *.cc set filetype=cpp

" Choose a colorscheme
" colorscheme sideWinder
colorscheme jellybeans

" Automatically break a line of the current line is too long
" set textwidth=120

" Line numbers
set number

" Highlights the matching brace/bracket under the cursor
set showmatch

" Highlight search matches
set hlsearch

" Turn off all bells (stops vim from beeping at you or flashing the screen)
set belloff=all
